```{r}
# Load the ape package
library(ape)

# Define the tree as a list and assign the class "phylo"
egtree <- list(
  edge = matrix(c(5, 1,
                  5, 2,
                  5, 6,
                  6, 3,
                  6, 4), ncol = 2, byrow = TRUE),
  tip.label = c("A", "B", "C", "D"),
  Nnode = 2,
  edge.length = c(0.1, 0.2, 0.3, 0.4, 0.5)
)
class(egtree) <- "phylo"

# Plot the tree
plot(egtree, main = "Reconstructed Tree")

plot.phylo(egtree, type = "unrooted", edge.color = "blue", edge.width = 2, tip.color = "red", main = "Customized Phylogenetic Tree")
```

```{r}
D = matrix(c(0,5,9,9,8,5,0,10,10,9,9,10,0,8,7,9,10,8,0,3,8,9,7,3,0), ncol=5)
# Calculate Q matrix
cal_Q <- function(D_matrix) {}
n = dim(D)[1]
st_m = matrix(0, ncol=n, nrow=n) # Standard matrix
diag(st_m) <- 1
Q = matrix(0, ncol=n, nrow=n)
trans_m = matrix(1, ncol=n, nrow=n)
d1 = D %*% trans_m
d2 = t(d1)
Q = (n-2) * D - d1 - d2
diag(Q) <- 0
min(Q)
cord = which(Q==-50,arr.ind=TRUE)[1,]
cord1 = cord[2]
cord2 = cord[1]
delta1 = 0.5 * D[cord1,cord2] + 0.5/(n-2)*(d1[cord1,cord2]-d2[cord1,cord2])
delta2 = D[cord1,cord2] - delta1

trans_m = st_m
trans_m[cord1,cord2] = 1
new_row = trans_m %*% D

trans_m = st_m
trans_m[cord1,] = -1
new_row = 0.5 * (new_row %*% trans_m)[cord1,c(-cord1, -cord2)]
D <- D[c(-cord1,-cord2),]
D <- D[,c(-cord1,-cord2)]
D <- rbind(new_row, D)
D <- cbind(c(0,new_row), D)
```


```{r}
NJ <- function(D_matrix, total_dim, edge_vector) {
  n = dim(D_matrix)[1]
  st_m = matrix(0, ncol=n, nrow=n) # Standard matrix
  diag(st_m) <- 1
  Q = matrix(0, ncol=n, nrow=n)
  trans_m = matrix(1, ncol=n, nrow=n)
  d1 = D_matrix %*% trans_m
  d2 = t(d1)
  Q = (n-2) * D_matrix - d1 - d2
  diag(Q) <- 0
  minQ <- min(Q)
  cord = which(Q==minQ, arr.ind=TRUE)[1,]
  cord1 = cord[2]
  cord2 = cord[1]
  
  edge1 = edge_vector[cord1]
  edge2 = edge_vector[cord2] # retrieve the edge values for joining taxa
  #if(n != total_dim) {
   # if(cord1 == 1) {
    #  edge1 = 2*total_dim-n # edge value for new node created in last iteration
    #}
  #} 
  delta1 = 0.5 * D_matrix[cord1,cord2] + 0.5/(n-2)*(d1[cord1,cord2]-d2[cord1,cord2])
  delta2 = D_matrix[cord1,cord2] - delta1
  
  if (n==3) {
    delta3 = D_matrix[1,3] - delta1 # it's for the last iteration which will omit 3 delta values. The last Q matrix must be a matrix with all equal values not in diagonal
    edge3 = edge_vector[3]
    return(list(c(edge1, edge2, edge3), c(delta1, delta2, delta3)))
  } # the last iteration would not need to update the D matrix and just return edge values and delta
  
  trans_m = st_m
  trans_m[cord1,cord2] = 1
  new_row = trans_m %*% D_matrix
  
  trans_m = st_m
  trans_m[cord1,] = -1
  new_row = 0.5 * (new_row %*% trans_m)[cord1,c(-cord1, -cord2)]

  D_matrix <- D_matrix[c(-cord1,-cord2),]
  D_matrix <- D_matrix[,c(-cord1,-cord2)] # delete 2 rows and 2 cols that belong to the 2 joined taxa
  edge_vector <- edge_vector[c(-cord1,-cord2)] # do the same on edge matrix
  edge_vector <- append(2*total_dim+1-n, edge_vector) # create a new edge value for new node
  D_matrix <- rbind(new_row, D_matrix)
  D_matrix <- cbind(c(0,new_row), D_matrix) # Always the new node is in the first col and row
  return(list(D_matrix, c(edge1, edge2), c(delta1, delta2), edge_vector))
}

edge <- c(1:5)
D = matrix(c(0,5,9,9,8,5,0,10,10,9,9,10,0,8,7,9,10,8,0,3,8,9,7,3,0), ncol=5)
t <- NJ(D, dim(D)[1], edge)
```


```{r}
NJ_iter <- function(D_init) {
  dim = dim(D_init)[1]
  edge_v = c(1:dim) # vector can be operated and record the edge values' changes
  edge <- matrix(0, ncol=2, nrow=2*dim-3)
  tip.label <- paste("t", 1:dim, sep='')
  Nnode = dim - 2
  edge.length <- c(rep(0, each=2*dim-3))
  for(i in dim:4) {
    out <- NJ(D_init, dim, edge_v)
    D_init <- out[[1]]
    print(D_init)
    edge[c(2*dim-2*i+1,2*dim-2*i+2),] <- c(2*dim+1-i, 2*dim+1-i, out[[2]][1], out[[2]][2])
    print(edge)
    edge.length[c(2*dim-2*i+1,2*dim-2*i+2)] <- out[[3]]
    print(edge.length)
    edge_v <- out[[4]]
  }
  print(edge_v)
  out <- NJ(D_init, dim, edge_v)
  edge[c(2*dim-5, 2*dim-4, 2*dim-3),] <- c(2*dim-2, 2*dim-2, 2*dim-2, out[[1]][1], out[[1]][2], out[[1]][3])
  print(edge)
  edge.length[c(2*dim-5, 2*dim-4, 2*dim-3)] <- out[[2]]
  print(edge.length)
  
  return(list("edge"=edge, "tip.label"=tip.label, "Nnode"=Nnode, "edge.length"=edge.length))
}

D = matrix(c(0,5,9,9,8,5,0,10,10,9,9,10,0,8,7,9,10,8,0,3,8,9,7,3,0), ncol=5)
tree <- NJ_iter(D)

class(tree) <- "phylo"
```


```{r}
# Plot the tree
plot(tree, main = "Reconstructed Tree")

plot.phylo(tree, type = "unrooted", edge.color = "blue", edge.width = 2, tip.color = "red", main = "Customized Phylogenetic Tree")
```



